feature: don't ask user confirmation when delete with --force or --yes
kubevela/kubevela pull request #4259
Opened 2022-06-25 14:35 UTC by sumit-tembe

Fixes #4258

2022-06-25 15:34 UTC, Somefive requested changes
hold it until this feature is fully discussed

2022-06-25 20:53 UTC, wonderflow commented on references/cli/delete.go
> +		o.ForceDelete = force || yes
you need to add a new flag to represent `yes`. `--force` and `--yes` are not the same.

2022-06-26 07:19 UTC, wonderflow approved these changes

2022-07-01 09:44 UTC, wonderflow commented on references/cli/delete.go
> +	cmd.PersistentFlags().BoolVarP(&o.Yes, "yes", "y", false, "assume yes for all user prompts")
there's already a global yes defined outside.

2022-07-06 07:32 UTC, wonderflow approved these changes

2022-07-06 07:34 UTC, merged