Feat: refactor CLI commands related to resources
kubevela/kubevela pull request #4500
Opened 2022-07-29 06:37 UTC by barnettZQG

Signed-off-by: barnettZQG <barnett.zqg@gmail.com>

### Description of your changes

Fixes #

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

### Special notes for your reviewer

2022-07-29 09:53 UTC, wonderflow requested changes
the `vela pods` command is confusing, let wrap it into 

```
vela status --pods
```

We already have:

```
vela status --tree
```

2022-07-29 10:28 UTC, barnettZQG commented
> the `vela pods` command is confusing, let wrap it into
> 
> ```
> vela status --pods
> ```
> 
> We already have:
> 
> ```
> vela status --tree
> ```

fixed.

2022-07-29 10:54 UTC, wonderflow commented on references/cli/portforward.go
> +		pt := o.targetPort
how do you get the targetPort if the resource is Pod

2022-07-29 10:55 UTC, wonderflow commented on pkg/velaql/providers/query/collector.go
> -func helmReleasePodCollector(cli client.Client, obj *unstructured.Unstructured, cluster string) ([]*unstructured.Unstructured, error) {
why not needed

2022-07-29 11:07 UTC, wonderflow approved these changes

2022-08-01 11:44 UTC, Somefive approved these changes

2022-08-01 11:44 UTC, merged