Feat: add feature docs and controller parameters for multiStageComponentApply
kubevela/kubevela pull request #4873
Opened 2022-10-16 14:40 UTC by ZhongsJie96

Signed-off-by: ZhongsJie <zhongsjie@gmail.com>

### Description of your changes

Fixes #

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

### Special notes for your reviewer

2022-10-17 02:14 UTC, Somefive approved these changes

2022-10-17 03:01 UTC, Somefive requested changes
Seems the helm install process will fail. Maybe caused by the incorrect space in L224 in kubevela-controller.yaml?

2022-10-23 16:35 UTC, ZhongsJie96 commented
> Seems the helm install process will fail. Maybe caused by the incorrect space in L224 in kubevela-controller.yaml?

Sorry I didn't reply in time. There is an incorrect capital letter in L224.

2022-10-25 06:51 UTC, Somefive approved these changes
Cool, great job!

2022-10-25 06:51 UTC, merged