Fix: delete the secret of the cluster
kubevela/kubevela pull request #5497
Opened 2023-02-14 02:14 UTC by suwliang3

Signed-off-by: suwanliang_yewu <suwanliang_yewu@cmss.chinamobile.com>

### Description of your changes

Fixes #5467 

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

### Special notes for your reviewer

2023-02-14 02:21 UTC, wonderflow requested changes
please add some test case for it

2023-02-14 02:49 UTC, Somefive commented on pkg/apiserver/domain/service/cluster.go
> +			if err = multicluster.DetachCluster(ctx, c.K8sClient, clusterName); err != nil {
The fallback code here should follow through to the logic below.

2023-02-14 03:00 UTC, nuclearwu commented
Please handle go/lint and go/ check-diff error

2023-02-16 03:55 UTC, Somefive approved these changes
Great job!

2023-02-16 03:55 UTC, Somefive commented
/cc @wonderflow

2023-02-16 05:35 UTC, wonderflow approved these changes
good job

2023-02-16 05:46 UTC, FogDong approved these changes
Should this be backported to 1.7?

2023-02-16 06:03 UTC, merged