Fix: length of name should be less than 32
kubevela/kubevela pull request #5547
Opened 2023-02-21 07:34 UTC by caiqi1111

### Description of your changes

Name can not be more than 31. When app name is `ab012345678901234567890123456789 `, I create it failed. 

Fixes #

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

### Special notes for your reviewer

2023-02-27 01:59 UTC, FogDong approved these changes

2023-03-01 01:45 UTC, barnettZQG requested changes
@caiqi1111 Please check the e2e test.

2023-03-03 07:42 UTC, caiqi1111 commented
@barnettZQG e2e-apiserver-test is ready now. please check again

2023-03-03 08:34 UTC, barnettZQG approved these changes
LGTM

2023-03-03 08:35 UTC, merged