fix:return the error when get the resource
kubevela/kubevela pull request #5611
Opened 2023-03-05 08:05 UTC by Feizekai

### Description of your changes

Fixes #

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

### Special notes for your reviewer

2023-03-07 03:12 UTC, Somefive commented
Could you give more details for why we need this PR? Like some usage example or scenario?

2023-03-07 03:15 UTC, Somefive commented
BTW, please fixes the DCO.

2023-03-16 02:04 UTC, wonderflow requested changes
we don't need to return the error as the function is checking if exists

2026-06-17 09:18 UTC, Reetika2509 commented
Hi @Feizekai — thanks for the contribution.

Taking a closer look: IsExist intentionally returns (false, nil) on IsNotFound — that's the expected "doesn't exist, no error" path, whilegenuine failures already return via return false, err. Returning an error on NotFound would change the contract and make callers treat alegitimate "not found" as a failure, so this would actually introduce a regression rather than fix one. That's along the lines of what @Somefive was asking about in the earlier comments.

Since the change isn't needed, I'm going to close it. If you hit a concrete scenario where IsExist swallows an error it shouldn't, please open an issue with the details and we'll be happy to look. Thanks again!

2026-06-17 09:24 UTC, Feizekai commented
> Hi @Feizekai — thanks for the contribution.
> 
> Taking a closer look: IsExist intentionally returns (false, nil) on IsNotFound — that's the expected "doesn't exist, no error" path, whilegenuine failures already return via return false, err. Returning an error on NotFound would change the contract and make callers treat alegitimate "not found" as a failure, so this would actually introduce a regression rather than fix one. That's along the lines of what @Somefive was asking about in the earlier comments.
> 
> Since the change isn't needed, I'm going to close it. If you hit a concrete scenario where IsExist swallows an error it shouldn't, please open an issue with the details and we'll be happy to look. Thanks again!

I got u.Its magically that u review the pr, even it has been 3 yrs😂

2026-06-24 05:44 UTC, closed without merging